export const env = {
  NEXT_PUBLIC_SANITY_PROJECT_ID: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'ti3ll1zm',
  NEXT_PUBLIC_SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET || 'project-annnimate',
  NEXT_PUBLIC_SANITY_API_VERSION: process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2024-01-01',

  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://tubyaixevxxihdksonof.supabase.co',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YnlhaXhldnh4aWhka3Nvbm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3NzE3ODEsImV4cCI6MjEwNDM0Nzc4MX0.NAIAwm_t2ioDlmDM3SH7iPQBb1iBe3e-gIplG7gfpR0',
};
